### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by jdinda70** [davide-romanini/unrar-cffi#1]
Davide ...

I am trying to get this installed via pip and manually installing via setup.py.  Both fail.  I have been trying to get it installed so that I can use the latest ComicTagger scripts (but luckily, you compiled the past few, so I don't need to run the scripts directly.

Running Python 3.6.8 on Windows.  Did a clean install just to make sure I something hadn't become corrupted.

I think I have all of the prereqs installed via pip:

pip list

Package        Version
-------------- ---------
altgraph       0.16.1
beautifulsoup4 4.8.1
configparser   4.0.2
future         0.18.1
natsort        3.5.2
pefile         2019.4.18
Pillow         6.2.0
pip            19.3.1
PyInstaller    3.5
PyPDF2         1.24
PyQt5          5.13.1
PyQt5-sip      12.7.0
pywin32-ctypes 0.2.0
setuptools     41.4.0
soupsieve      1.9.4

PIP install results:

C:\Users\Administrator.Vuze>pip install unrar-cffi==0.1.0a5
Collecting unrar-cffi==0.1.0a5
  Using cached https://files.pythonhosted.org/packages/32/6b/5f6cffd8e30304d160933342214c097bb7dca9d52bd6cf14a1678b2ea0b9/unrar-cffi-0.1.0a5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1.VUZ\\AppData\\Local\\Temp\\pip-install-rrhitmet\\unrar-cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1.VUZ\\AppData\\Local\\Temp\\pip-install-rrhitmet\\unrar-cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1.VUZ\AppData\Local\Temp\pip-install-rrhitmet\unrar-cffi\pip-egg-info'
         cwd: C:\Users\ADMINI~1.VUZ\AppData\Local\Temp\pip-install-rrhitmet\unrar-cffi\
    Complete output (44 lines):
    warning: no previously-included files found matching 'setup.pyc'
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.__pycache__.lex.cpython-36: module references __file__
    pycparser.ply.__pycache__.lex.cpython-36: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-36: module references __file__
    pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.getsourcefile
    pycparser.ply.__pycache__.yacc.cpython-36: module MAY be using inspect.stack
    pycparser.ply.__pycache__.ygen.cpython-36: module references __file__

    Installed c:\users\admini~1.vuz\appdata\local\temp\pip-install-rrhitmet\unrar-cffi\.eggs\pycparser-2.19-py3.6.egg
    preprocessing extension headers
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1.VUZ\AppData\Local\Temp\pip-install-rrhitmet\unrar-cffi\setup.py", line 63, in <module>
        python_requires='>=3.4'
      File "c:\program files\python36\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python36\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\program files\python36\lib\site-packages\setuptools\dist.py", line 447, in __init__
        k: v for k, v in attrs.items()
      File "c:\program files\python36\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "c:\program files\python36\lib\site-packages\setuptools\dist.py", line 735, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\admini~1.vuz\appdata\local\temp\pip-install-rrhitmet\unrar-cffi\.eggs\cffi-1.13.0-py3.6-win-amd64.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\admini~1.vuz\appdata\local\temp\pip-install-rrhitmet\unrar-cffi\.eggs\cffi-1.13.0-py3.6-win-amd64.egg\cffi\setuptools_ext.py", line 57, in add_cffi_module
        ffi = ffi()      # maybe it's a function instead of directly an ffi
      File "buildconf.py", line 77, in create_builder
        preprocess = subprocess.check_output(PREPROCESS_CMD, universal_newlines=True)
      File "c:\program files\python36\lib\subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "c:\program files\python36\lib\subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\program files\python36\lib\subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "c:\program files\python36\lib\subprocess.py", line 1017, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

when I try to run setup.py in the repository clone, I get this:

python setup.py
Traceback (most recent call last):
  File "setup.py", line 63, in <module>
    python_requires='>=3.4'
  File "C:\Program Files\Python36\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\Python36\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Program Files\Python36\lib\site-packages\setuptools\dist.py", line 447, in __init__
    k: v for k, v in attrs.items()
  File "C:\Program Files\Python36\lib\distutils\dist.py", line 281, in __init__
    self.finalize_options()
  File "C:\Program Files\Python36\lib\site-packages\setuptools\dist.py", line 735, in finalize_options
    ep.load()(self, ep.name, value)
  File "c:\users\administrator.vuze\desktop\git\unrar-cffi\.eggs\cffi-1.13.0-py3.6-win-amd64.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "c:\users\administrator.vuze\desktop\git\unrar-cffi\.eggs\cffi-1.13.0-py3.6-win-amd64.egg\cffi\setuptools_ext.py", line 57, in add_cffi_module
    ffi = ffi()      # maybe it's a function instead of directly an ffi
  File "buildconf.py", line 77, in create_builder
    preprocess = subprocess.check_output(PREPROCESS_CMD, universal_newlines=True)
  File "C:\Program Files\Python36\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python36\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Not sure what is wrong or how to fix.

**Comment by davide-romanini** [comment]
I seems you are trying to install from source distribution, and not via wheel.
That means you'll need a bunch of Visual Studio related packages, such as the MSBuild tools, the Visual C++ compiler suite and the Windows SDK.
Since that's not so trivial, and the exact reason I created the project is to create wheels so end users don't need to go that path, I wonder why your pip doesn't fetch the correct package.
Maybe adding `--only-binary` could help?

**Comment by jdinda70** [comment]
I did install Visual Studio Build Tools 2017 and (think) I installed the
Visual C++ compiler suite (not sure about the Windows SDK ... will check).

does this look right to you?

[image: image.png]

I can't figure out how/where to use the --only-binary option.

**Comment by davide-romanini** [comment]
Try with [`pip --only-binary=:all:`](https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-only-binary).
The windows x86_64 wheel should be used automatically, maybe you are running on 32bit windows version? Just a thought.

As a side note, I created a [gitter community](https://gitter.im/comictagger/community) and a [discussion group](https://groups.google.com/forum/#!forum/comictagger). I think they are a more appropriate way to discuss this problems, and keep the github issues focused only on actual "TODO" activities. :-)

**Comment by jdinda70** [comment]
running 64-bit windows

I tried --only-binary (I think correctly.  no luck).  see below

C:\Users\Administrator>pip install --only-binary=:all: unrar-cffi
ERROR: Could not find a version that satisfies the requirement unrar-cffi
(from versions: none)
ERROR: No matching distribution found for unrar-cffi

C:\Users\Administrator>pip install unrar-cffi --only-binary=:all:
ERROR: Could not find a version that satisfies the requirement unrar-cffi
(from versions: none)
ERROR: No matching distribution found for unrar-cffi

i'll check out those other links.  thank you.

**Comment by jdinda70** [comment]
I looked at those two sites.  This issue isn't really with ComicTagger.
It's with unrar-cffi, but I can post it there if you like.

**Comment by davide-romanini** [comment]
Hi @jdinda70, 
I admit I'm experimenting with different ways to discuss on these projects, so feel free to join there to share more ideas and find help. :-)

By the way, currently I only build wheels for Python 3.7 on windows. The easiest solution is to upgrade to that version of python, if it's feasible.

If you **really** want to compile it on your own, you should carefully study how it's [built on TravisCI](https://github.com/davide-romanini/unrar-cffi/blob/develop/.travis.yml). 
Pay particular attention to the [build_win.bat](https://github.com/davide-romanini/unrar-cffi/blob/develop/build_win.bat) that wraps the calls into the [VS Developer Command Prompt](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs), bringing up the needed environment variables to the various compilers and build tools.

**Comment by jdinda70** [comment]
thanks Davide!  good to know about Python3.7

**Comment by jdinda70** [comment]
FYI.  moving to Python 3.7 resolved the issue.  unrar-cffi and comictagger
pip installs both worked after that.  thank you!

**Comment by kanine** [comment]
I've been getting this same issue, have tried the command as below, as well as installing the Build Tools but getting the same error you had, but with Python 3.8.2 / Windows 10 64 Bit

```
py -m pip install --only-binary=:all: unrar-cffi==0.1.0a5
ERROR: Could not find a version that satisfies the requirement unrar-cffi==0.1.0a5 (from versions: none)
ERROR: No matching distribution found for unrar-cffi==0.1.0a5
```

**Comment by rg9400** [comment]
Would like to also mention that I cannot install this on Python 3.8.2 on Windows 10 64bit. It seems like the Windows wheel wasn't built for cp38 (https://pypi.org/project/unrar-cffi/#files).

Anyone have any workaround to get it working with Python 3.8? I would rather not downgrade to 3.7

**Comment by SleepingPanda** [comment]
Having the same issues with Python 3.11.4 on Windows 11. Is there any way to solve these issues without downgrading to python 3.7, @davide-romanini ?
