### ISSUE TITLE
Package name conflict

### ISSUE THREAD

**Issue by tlc** [davide-romanini/unrar-cffi#2]
I think your new package conflicts with an older one.

```
$ ./comictagger.py
Traceback (most recent call last):
  File "./comictagger.py", line 2, in <module>
    from comictaggerlib.main import ctmain
  File "/Users/troy/CT/comictaggerlib/main.py", line 36, in <module>
    from . import cli
  File "/Users/troy/CT/comictaggerlib/cli.py", line 33, in <module>
    from .options import Options
  File "/Users/troy/CT/comictaggerlib/options.py", line 30, in <module>
    from .comicarchive import MetaDataStyle
  File "/Users/troy/CT/comictaggerlib/comicarchive.py", line 1, in <module>
    from comicapi.comicarchive import *
  File "/Users/troy/CT/comicapi/comicarchive.py", line 29, in <module>
    from unrar.cffi import rarfile
ModuleNotFoundError: No module named 'unrar.cffi'
```

```
$ pip3 freeze |grep unrar
unrar==0.3
unrar-cffi==0.1.0a5
```
```
$ pip3 uninstall unrar
```

And commictagger works.

**Comment by davide-romanini** [comment]
Yes, the `unrar` package is no longer required and is replaced by this one. In latest comictagger the `requirements.txt` no longer inlude the old package, so it's not an issue.

**Comment by tlc** [comment]
But what if people are using unrar for other reasons?

**Comment by davide-romanini** [comment]
The idea of this project is to be a replacement for unrar package, since
they do the same thing using a different technique. I don't see any reason
to have them coexist.

Il Mer 19 Ago 2020, 05:20 tlc <notifications@github.com> ha scritto:

**Comment by tlc** [comment]
Scenario:

1. I install comictagger, which installs unrar-cffi.
2. I install 3 other projects, which have requirements.txt or setup.py files that install unrar.
3. Comictagger is now broken.

**Comment by davide-romanini** [comment]
You should never install anything on a shared pip environment, always setup a virtual environment or try [pipx](https://pipxproject.github.io/pipx/).
