### ISSUE TITLE
need a isdir method on RarInfo

### ISSUE THREAD

**Issue by bbtfr** [davide-romanini/unrar-cffi#4]
Just like zipfile or tarfile, it's worth to have a `isdir` method on RarInfo

Something like `header.Flags & RHDF_DIRECTORY == RHDF_DIRECTORY`

**Comment by e-boroda** [comment]
RarInfo.flag_bits == 32  _works for me_.

**Comment by davide-romanini** [comment]
I added it to the latest release 0.2.1.

Thank you.
